[package]
name = "prop-amm"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Linear Prop AMM for Solana"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
std = []

[dependencies]
pinocchio = { workspace = true, features = ["cpi"] }
c_u_soon = { path = "../../../sdk", features = ["derive"] }
c_u_later = { path = "../../../c_u_later", features = ["derive"] }
bytemuck = { version = "1.25", features = ["derive", "min_const_generics"] }
c_u_soon_cpi = { path = "../../../cpi" }

[dev-dependencies]
mollusk-svm = "0.10"
mollusk-svm-programs-token = "0.10"
solana-sdk = "3.0"
